name: Build

on:
  push:
    branches:
      - master
    tags:
      - '**'
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - '*.png'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - '*.png'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 17 ]
    name: Build with JDK ${{matrix.java}}

    steps:
      ## - name: Display Github Event Context
      ##   run: echo "$GITHUB_CONTEXT"
      ##   env:
      ##     GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK ${{matrix.java}}
        uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.java}}

      - name: Cache Maven Packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Maven Build
        run: mvn -B verify

      ## Save the context information for use in Sonar analysis
      - name: Save Build Context
        if: matrix.java == '17'
        run: echo "$GITHUB_CONTEXT" > target/build-context.json
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      ## Attach the target directory for use in Sonar analysis
      - name: Attach Build Output
        if: matrix.java == '17'
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: target/

  javadoc:
    runs-on: ubuntu-latest
    name: Verify JavaDocs

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Generate JavaDocs
        run: mvn -B package javadoc:javadoc -DskipTests
