name: StAEDI Build

on:
  push:
    paths-ignore:
      - '.gitignore'
      - '.travis.yml'
      - 'ci_build.sh'
      - 'ci_coverage.sh'
      - 'LICENSE'
      - 'README*'
      - '*.png'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - '.travis.yml'
      - 'ci_build.sh'
      - 'ci_coverage.sh'
      - 'LICENSE'
      - 'README*'
      - '*.png'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]
    name: Build with JDK ${{matrix.java}}

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-java@v1.3.0
        name: Set up JDK ${{matrix.java}}
        with:
          java-version: ${{matrix.java}}

      - name: Maven build
        run: mvn -B verify package javadoc:javadoc --file pom.xml

  quality:
    needs: [build]
    if: github.event_name == 'push' && github.repository == 'xlate/staedi'
    runs-on: ubuntu-latest
    name: Quality

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: 11

      - name: Sonar
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        run: mvn -B verify --file pom.xml -Pcoverage sonar:sonar -Dsonar.projectKey=xlate_staedi -Dsonar.login=$SONAR_TOKEN
