name: StAEDI Build

on:
  push:
    paths-ignore:
      - '.gitignore'
      - '.travis.yml*'
      - 'ci_build.sh'
      - 'ci_coverage.sh'
      - 'LICENSE'
      - 'README*'
      - '*.png'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - '.travis.yml*'
      - 'ci_build.sh'
      - 'ci_coverage.sh'
      - 'LICENSE'
      - 'README*'
      - '*.png'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]
    name: Build with JDK ${{matrix.java}}

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-java@v1.3.0
        name: Setup JDK ${{matrix.java}}
        with:
          java-version: ${{matrix.java}}

      - name: Maven build
        run: mvn -B verify package --file pom.xml

      - name: Generate Coveralls File
        if: matrix.java == '11'
        run: mvn -B coveralls:report -Pcoverage -DdryRun=true

      - name: Coveralls Analysis
        if: matrix.java == '11'
        uses: MikeEdgar/github-action@raw_coverage_file
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-file: ./target/coveralls.json
          coverage-format: raw

  javadoc:
    runs-on: ubuntu-latest
    name: Verify JavaDocs

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: 11

      - name: Generate JavaDocs
        run: mvn -B verify javadoc:javadoc --file pom.xml

  quality:
    if: github.event_name == 'push' && github.repository == 'xlate/staedi'
    runs-on: ubuntu-latest
    name: Verify Quality

    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow --tags

      - uses: actions/setup-java@v1.3.0
        with:
          java-version: 11

      - name: SonarCloud Analysis
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        run: mvn -B verify --file pom.xml sonar:sonar -Dsonar.projectKey=xlate_staedi -Dsonar.login=$SONAR_TOKEN
